### PR TITLE
Larger callouts to work at and with Shopify

### PR DESCRIPTION
**Pull request by shawnfrench**
@cshold what do you think about adding larger callouts to work at Shopify and add a new one to work with Shopify (developer program)? Would you be able to help in the design as I'm obviously lacking any/all skills in that dept :smile: 

screen shot 2015-08-26 at 11 50 42 am

cc @atleeclark

### CODE REVIEW

**Comment by cshold** [comment]
Great addition. Let's loop in @tranhelen - are you able to lend a bit of design help?

**Comment by tranhelen** [comment]
This looks alright with me for now but I would change the titles. They're too similar to each other and they can easily get glossed over.

**Comment by shawnfrench** [comment]
Ha yeah maybe `Work at Shopify` and `Develop with Shopify`? @atleeclark or @fditrapani thoughts?

**Comment by fditrapani** [comment]
"Work at Shopify" is good. How about this for app developers: 

### Join our developer community
Our app developers have earned millions of dollars developing apps for the Shopify App Store. Starting building apps and reach over 175,000 merchants.
_Learn more_

**Comment by shawnfrench** [comment]
Updated copy - but could still use some CSS love I think...
Mobile:
mobile

Desktop:
desktop

**Comment by fditrapani** [comment]
All you need is some space after the banner on the desktop so that the copy right info and links aren't butting up against it like this:
desktop

And on mobile, just add some space after the "work at Shopify" paragraph, like so:
desktop

**Comment by shawnfrench** [comment]
OK...can you please do that simple thing @fditrapani? Me no css.

**Comment by shawnfrench** [comment]
Thanks to @fditrapani 's mad CSS skills I think this is ready to go. @carsonb good to ship?

**Comment by cshold** [comment]
Looks good :+1:

**Pull request merged**
