### PR TITLE
Included FunctionalTableData to the list

### PR DESCRIPTION
**Pull request by raulriera**
## What

Included FunctionalTableData to the list of projects

### CODE REVIEW

**Comment by beefchimi** [comment]
Hey there! Any chance you could just commit a single white space change to the `index.html`? I believe you need this for your new entry to show up.

Reference:
https://github.com/Shopify/shopify.github.com/pull/56/files#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by raulriera** [comment]
Updated, thanks for the info!

**Comment by beefchimi** [comment]
This looks solid to me 👍  you should be safe to merge.

For some reason I can not run the repo locally... I think since updating to High Sierra I still have some kind of gem crisis.

Why don't you merge and let me know. Then we can both check the live site and make sure all is good.

**Comment by raulriera** [comment]
Maybe it takes a while to show up? I don't see any other "Swift" project, so maybe there is something else to add?

**Comment by beefchimi** [comment]
Workin for me :)

screen shot 2017-11-23 at 1 25 54 pm

**Comment by raulriera** [comment]
Awesome! thanks for your help

**Pull request merged**
